# Generated by Django 5.1.3 on 2024-11-07 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Notification', '0001_initial'),
        ('Office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='Office.office'),
        ),
    ]
