# Generated by Django 5.1.2 on 2024-11-06 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Office', '0002_initial'),
        ('User', '0002_remove_adminuser_office_remove_baseuser_photo_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='User.user'),
        ),
    ]
