# Generated by Django 5.1.3 on 2024-11-07 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Office', '0004_case_lawyer_alter_case_office_alter_case_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legaldocument',
            name='file_path',
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='file',
            field=models.FileField(null=True, upload_to='legal_documents'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_documents_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
