# Generated by Django 5.1.2 on 2024-11-06 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Office', '0002_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='office',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='photo_path',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='office',
        ),
        migrations.RemoveField(
            model_name='user',
            name='office',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='Office.office'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='id_document',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
